[package]
name = "fp-ethereum"
version = "1.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
description = "Primitive Ethereum types."
repository = "https://github.com/paritytech/frontier/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ethereum = { version = "0.14.0", default-features = false, features = ["with-codec"] }
ethereum-types = { version = "0.14.0", default-features = false }
fp-evm = { version = "3.0.0-dev", path = "../evm", default-features = false }
num_enum = { version = "0.5.4", default-features = false }

# Parity
codec = { package = "parity-scale-codec", version = "3.2.1", default-features = false }

# Substrate
sp-core = { git = "https://github.com/humanode-network/substrate", branch = "locked/humanode-2022-11-23", default-features = false }
sp-std = { git = "https://github.com/humanode-network/substrate", branch = "locked/humanode-2022-11-23", default-features = false }
# Substrate FRAME
frame-support = { git = "https://github.com/humanode-network/substrate", branch = "locked/humanode-2022-11-23", default-features = false }

[features]
default = ["std"]
std = [
	"ethereum/std",
	"ethereum-types/std",
	"num_enum/std",
	# Parity
	"codec/std",
	# Substrate
	"sp-core/std",
	"sp-std/std",
	# Substrate FRAME
	"frame-support/std",
]
