[package]
name = "pallet-evm-test-vector-support"
version = "1.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
description = "Test vector support for EVM pallet."
repository = "https://github.com/paritytech/frontier/"

[dependencies]
evm = { version = "0.37.0", features = ["with-codec"] }
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Substrate
sp-core = { git = "https://github.com/humanode-network/substrate", branch = "patch-pallet-error-macro-clippy-cast-possible-truncation" }

# Frontier
fp-evm = { version = "3.0.0-dev", path = "../../../primitives/evm" }
